# Generated by Django 5.1.7 on 2025-03-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAdd',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('user_level', models.CharField(default='admin', max_length=10)),
            ],
            options={
                'ordering': ['account_id'],
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
