# Generated by Django 5.1.7 on 2025-03-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_useradd_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useradd',
            name='user_level',
        ),
        migrations.AddField(
            model_name='useradd',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin')], default='admin', max_length=10),
        ),
    ]
