# Generated by Django 5.1.7 on 2025-03-20 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_useradd_user_level_useradd_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useradd',
            old_name='role',
            new_name='user_level',
        ),
    ]
