# Generated by Django 5.1.7 on 2025-03-22 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_role_useradd_user_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useradd',
            options={'managed': False},
        ),
    ]
