# Generated by Django 5.1.7 on 2025-03-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_useradd_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('announcement_id', models.AutoField(primary_key=True, serialize=False)),
                ('announcement_title', models.CharField(max_length=100)),
                ('announcement_content', models.TextField()),
                ('announcement_start_date', models.DateTimeField(auto_now_add=True)),
                ('announcement_end_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'announcement_tbl',
                'managed': False,
            },
        ),
    ]
