# Generated by Django 5.1.7 on 2025-04-17 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_announcements'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('room_number', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('map_key', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'room_tbl',
                'managed': False,
            },
        ),
    ]
