# Generated by Django 5.1.7 on 2025-04-17 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_room'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='room',
            table='navigation_tbl',
        ),
    ]
