# Generated by Django 5.1.7 on 2025-05-04 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
