# Generated by Django 5.1.7 on 2025-05-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_delete_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('student', 'Student'), ('employee', 'Employee'), ('parent', 'Parent/Guardian'), ('visitor', 'Visitor')], max_length=20)),
                ('clarity', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('normal', 'Normal'), ('needs_improvement', 'Needs improvement')], max_length=20)),
                ('ease', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('normal', 'Normal'), ('needs_improvement', 'Needs improvement')], max_length=20)),
                ('overall', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('normal', 'Normal'), ('needs_improvement', 'Needs improvement')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'feedback_tbl',
                'managed': True,
            },
        ),
    ]
