# Generated by Django 5.1.7 on 2025-05-04 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=20, unique=True)),
                ('text', models.TextField()),
            ],
            options={
                'db_table': 'question_tbl',
                'managed': True,
            },
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='clarity',
            new_name='clarity_rating',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='ease',
            new_name='ease_rating',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='overall',
            new_name='overall_rating',
        ),
        migrations.AddField(
            model_name='feedback',
            name='clarity_question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='clarity_feedbacks', to='users.question'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='ease_question',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='ease_feedbacks', to='users.question'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='overall_question',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, related_name='overall_feedbacks', to='users.question'),
        ),
    ]
