# Generated by Django 5.1.7 on 2025-05-04 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_question_rename_clarity_feedback_clarity_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='clarity_question',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='ease_question',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='overall_question',
        ),
    ]
