# Generated by Django 5.1.7 on 2025-05-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_feedback_clarity_question_feedback_ease_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='clarity_rating',
            field=models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('normal', 'Normal'), ('needs improvement', 'Needs improvement')], max_length=20),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='ease_rating',
            field=models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('normal', 'Normal'), ('needs improvement', 'Needs improvement')], max_length=20),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='overall_rating',
            field=models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('normal', 'Normal'), ('needs improvement', 'Needs improvement')], max_length=20),
        ),
    ]
