# Generated by Django 5.1.7 on 2025-05-13 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_remove_feedback_clarity_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='clarity_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clarity_feedback', to='users.question'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='clarity_rating',
            field=models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('normal', 'Normal'), ('needs improvement', 'Needs improvement')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='ease_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ease_feedback', to='users.question'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='ease_rating',
            field=models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('normal', 'Normal'), ('needs improvement', 'Needs improvement')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='overall_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='overall_feedback', to='users.question'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='overall_rating',
            field=models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('normal', 'Normal'), ('needs improvement', 'Needs improvement')], max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='FeedbackResponse',
        ),
    ]
