# Generated by Django 5.1.7 on 2025-05-13 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_feedback_clarity_question_feedback_clarity_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='clarity_question',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='clarity_rating',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='ease_question',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='ease_rating',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='overall_question',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='overall_rating',
        ),
        migrations.CreateModel(
            name='FeedbackResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('normal', 'Normal'), ('needs improvement', 'Needs improvement')], max_length=20)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='users.feedback')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_responses', to='users.question')),
            ],
            options={
                'db_table': 'feedback_response_tbl',
                'managed': True,
                'indexes': [models.Index(fields=['feedback', 'question'], name='feedback_re_feedbac_295ab9_idx')],
                'unique_together': {('feedback', 'question')},
            },
        ),
    ]
