# Generated by Django 5.1.7 on 2025-05-14 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_remove_feedback_clarity_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='key',
        ),
    ]
